# A class is a blueprint for an object that contains some data 
# (an attribute/field) and functions (methods)
#objects are instances of a class that contain data and functions.
#instance - copy or spawn. "concrete copy" that is generated by a class.
# An object is very flexable in that it can be made to look in a variety of ways.
# objects are supposed to represent some type of concrete thing in the real world

# To use a class we musft first define it (like a function)
class MyClass:
    #attributes - aka variables within the class
    x = 5

    #classes are supposed to be like blueprints. We can use variables within a class to be "copied" into new instances.

instance1 = MyClass() #creates an instance of MyClass (copy)
print(instance1.x) #access our attributes using dot(.) notation

instance2 = MyClass()
instance2.x = instance2.x -1
print(instance2.x)